name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-react:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup git config
        run: |
          git config user.name "Abhishek Yadav"
          git config user.email "abhishekisonit@gmail.com"

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Install dependencies and build with Vite
      - name: setup react deployment
        run: |
          cd react
          npm install
          rm -rf dist
          npm run build
          git add dist -f
          git commit -m "react build files - github action"
          git push
          cd ..
